pipeline {
    agent any
    
    tools {
        nodejs 'NodeJS 20'
    }
    
    environment {
        GITHUB_REPO = 'https://github.com/szabopatrik1204/music-app.git'
        BRANCH = 'main'
        SONAR_HOST_URL = "http://sonarqube:9000"
        SONAR_TOKEN = credentials('SONAR_TOKEN')
        IMAGE_NAME = 'music-app'
        IMAGE_TAG  = 'latest'
    }
    
    stages {

        stage('Checkout') {
            steps {
                retry(3) {
                    git branch: env.BRANCH, url: env.GITHUB_REPO
                }
            }
        }
        /*
        stage('SonarQube Analysis') {
            steps {
                withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                    dir('server') {
                        sh """
                  echo "=== Debug: current dir content ==="
                  ls -R
                  docker run --rm --network devops_default \
                    -v \$PWD:/usr/src \
                    sonarsource/sonar-scanner-cli \
                    -Dsonar.projectKey=music-app \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=$SONAR_HOST_URL \
                    -Dsonar.login=$SONAR_TOKEN
                    """
                    }
                }
            }
        }
        */
        
        stage('Build Docker Image') {
            steps {        
                dir('server') {
                    script {
                        sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                    }
                }
            }
        }
        
        stage('HadoLint Server Dockerfile') {
            steps {
                dir('server') {
                    sh '''
                        echo "=== Hadolint Dockerfile check ==="
                        echo "--- Dockerfile content ---"
                        cat Dockerfile
                        echo "--- End of Dockerfile ---"
        
                        echo "=== Hadolint version ==="
                        docker run --rm hadolint/hadolint hadolint --version
        
                        echo "=== Running Hadolint ==="
                        cat Dockerfile | docker run --rm -i hadolint/hadolint hadolint --failure-threshold error -
                    '''
                }
            }
        }
        
        stage('HadoLint Client Dockerfile') {
            steps {
                dir('client/my-first-project') {
                    sh '''
                        echo "=== Hadolint Client Dockerfile check ==="
                        echo "--- Client Dockerfile content ---"
                        cat Dockerfile
                        echo "--- End of Client Dockerfile ---"
        
                        echo "=== Hadolint version ==="
                        docker run --rm hadolint/hadolint hadolint --version
        
                        echo "=== Running Hadolint on Client ==="
                        cat Dockerfile | docker run --rm -i hadolint/hadolint hadolint --failure-threshold error -
                    '''
                }
            }
        }

        stage('Scan Image with Trivy') {
            steps {
                dir('server') {
                    script {
                        sh """
                            docker run --rm \
                              -v /var/run/docker.sock:/var/run/docker.sock \
                              aquasec/trivy:latest image \
                              --severity HIGH,CRITICAL \
                              ${IMAGE_NAME}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }

        stage('Backend Install Dependencies') {
            steps {
                dir('server') {
                    sh 'npm install'
                }
            }
        }
  
        stage('ESLint') {
            steps {
                dir('server') {
                    sh 'npm run lint'
                }
            }
        }
 
        stage('Backend Test') {
            steps {                
                dir('server') {
                    sh '''
                    npm run
                    npm run testci
                    '''
                }
            }
        }
        
        stage('Publish JUnit Results') {
            steps {
                junit 'server/junit.xml'
            }
        }

        stage('Backend Build') {
            steps {
                dir('server') {
                    sh 'npm run build'
                }
            }
        }
        
        stage('Archive Backend Artifacts') {
            steps {
                archiveArtifacts artifacts: 'server/build/**/*', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                dir('devops') {
                    sh '''
                    docker compose up -d
                    docker ps -a
                    '''
                }
            }
        }

        stage('Cleanup') {
            steps {
                deleteDir()
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline sikeresen lefutott!'
        }
        failure {
            echo 'Pipeline végrehajtása sikertelen volt!'
        }
    }
    
}