pipeline {
    agent any
    
    tools {
        nodejs 'NodeJS 20'
    }
    
    environment {
        GITHUB_REPO = 'https://github.com/szabopatrik1204/music-app.git'
        BRANCH = 'main'
        JENKINS_PUB_KEY = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAeCmsEBpZRJMaqnPz9Ohldzs4MOxm1tWf7NREdzsk5J jenkins-deploy'
    }
    
    stages {

        stage('Checkout') {
            steps {
                git branch: env.BRANCH, url: env.GITHUB_REPO
            }
        }
        
        stage('Backend Install Dependencies') {
            steps {
                dir('server') {
                    sh 'npm install'
                }
            }
        }
  
        stage('Lint') {
            steps {
                dir('server') {
                    sh 'npm run lint'
                }
            }
        }
 
        stage('Backend Test') {
            steps {                
                dir('server') {
                    sh 'npm run test'
                }
            }
        }

        stage('Backend Build') {
            steps {
                dir('server') {
                    sh 'npm run build'
                }
            }
        }
        
        stage('Archive Backend Artifacts') {
            steps {
                archiveArtifacts artifacts: 'server/build/**/*', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                dir('devops') {
                    sh 'docker compose up -d --build'
                }
            }
        }

        stage('Cleanup') {
            steps {
                deleteDir()
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline sikeresen lefutott!'
        }
        failure {
            echo 'Pipeline végrehajtása sikertelen volt!'
        }
    }
    
}