FROM mongo:6.0.9

EXPOSE 27017

# BUILD: sudo docker build -t my_mongo_image .
# RUN: sudo docker run -p 6000:27017 -it --name my_mongo_container -d my_mongo_image

# BUILD: sudo docker build -t mongo_db_6.0.9 .
# RUN: sudo docker run -p 6000:27017 -it --name mongo_container_6.0.9 -d mongo_db_6.0.9

# BUILD: sudo docker build -t mongo_db_5.9.1 .
# RUN: sudo docker run -p 6000:27017 -it --name mongo_container_5.9.1 -d mongo_db_5.9.1